[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[project]
name = "brachyutils"
version = "0.9.0"
description = "Python utility packages for handling dose files and egsphant files."
authors = [{name = "EngerLab"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "setuptools",
    "cycler",
    "fonttools",
    "importlib-resources",
    "kiwisolver",
    "pybind11",
    "numpy",
    "matplotlib",
    "packaging",
    "pandas",
    "Pillow",
    "pyparsing",
    "python-dateutil",
    "pytz",
    "cmake",
    "scikit-build",
    "SimpleITK",
    "pynrrd @ git+https://github.com/mhe/pynrrd.git",
    "six",
    "tzdata",
    "zipp",
    "pyzstd",
    "typer",
    "tqdm",
    "DicomRTTool",
    "pydicom",
    "scipy",
    "tk",
    "pymedphys",
    "py7zr",
    "pytest",
    "vtk",
    # comment out for docker build{
    "opentps @ git+https://github.com/engerlab/OpenTPS-brachyutils.git",
    # }
    "nibabel",
    "pydantic",
    "scikit-learn",
    "amplpy",
    "gurobipy",
    "ortools",
    "rtree",
    "trimesh[easy]",
    "python-fcl",
]

[project.optional-dependencies]
core = []
reg = ["monai"]
plan = ["gurobipy", "amplpy", "ortools"]
full = ["monai", "gurobipy", "amplpy", "ortools"]

[tool.setuptools.packages.find]
include = ["brachyutils.*", "brachyutils", "admin", "admin.*"]

[project.scripts]
brachyutils = "brachyutils.cli_utils:main"

[tool.setuptools.package-data]
"admin" = ["constants/*.json"]
