from setuptools import find_packages, setup
from os import getcwd

setup(
    name="brachyutils",
    version="1.0",
    description="Python utility packages for handling dose files and egsphant files.",
    author="EngerLab",
    packages=find_packages(),
    install_requires=[
        # "contourpy",
        "cycler",
        "fonttools",
        "importlib-resources",
        "kiwisolver",
        "pybind11",
        "numpy",
        "matplotlib",
        "packaging",
        "pandas",
        "Pillow",
        "pyparsing",
        "python-dateutil",
        "pytz",
        "cmake",
        "scikit-build",
        "SimpleITK",
        "six",
        "tzdata",
        "zipp",
        "pyzstd",
        "typer",
        "tqdm",
        "DicomRTTool",
        "pydicom",
        "scipy",
        "tk",
        "pymedphys",
        "py7zr",
        "pytest",
    ],
    package_dir={"":"/home/odcus/Software/brachyutils/brachyutils/src/"},
    entry_points={"console_scripts": ["brachyutils=cli_utils:main"]},
)
