from glob import glob
import json
import os
from tqdm import tqdm
import pytest
import typer
import numpy as np
import re
import gc

from dicom_utils import  get_structure_index_range
from egsphant_utils import _load_json, BrachyEgsphant
from dose_utils import BrachyDose
from plan_utils import BrachyPlan

from typing import Optional
from typing_extensions import Annotated

from multiprocessing import Pool
from functools import partial
app = typer.Typer()

@app.command(
    help="""Purpose: to exract body contour extent on each axis
    for all the patients in input_dir and save them to a json 
    file located at output_json""")
def get_bodyContourRange_from_dicom_many_patients(
    input_dir:Annotated[str, typer.Argument(
    help="""
    path to the directory where folders of many patients with dicom files exist. this script will loop through patient folders. \n
    Example:
    input_dir/p1/,
    input_dir/p2/ ...""")], 
    pth_output_json:Annotated[str, typer.Argument(
        help="""path to the json file where the following 
        information for each patient is stored""")] 
):
    r"""
    Purpose:
        to exract body contour extent on each axis for all the patients in input_dir and save them
        to a json file located at "output_json"
    Input:
        - input_dir := path to the directory where folders of many patients with dicom files exist.
            this script will loop through patient folders. Example:
                input_dir/p1/
                input_dir/p2/ ...
        - output_json := path to the json file where the following information for each patient is stored            
    Output: 
        - Void := the following content will be written to output_json for each patient:
            {
                patient_number:=str,
                body_index_range:[
                    [x_min:int, x_max:int],
                    [y_min:int, y_max:int],
                    [z_min:int, z_max:int],
                ]
                body_mask_shape:[len(x):int, len(y):int, len(z):int]
            }
    """

    input_dir = os.path.abspath(input_dir)
    
    patient_dir_list = glob(input_dir+"/*/")
    patient_dict_list = []
    
    for patient_dir in patient_dir_list:
        try:
            body_mask_info = get_structure_index_range(patient_dir, query_structure_list=["body"])
            body_index_range  = body_mask_info["body"]['structure_index_range']
            body_mask_shape = body_mask_info["body"]['dicom_mask_shape']
            patient_dict_list.append(
            {
            "patient_number": patient_dir.split("/")[-2],
            "body_index_range": body_index_range.tolist(),
            "body_mask_shape": body_mask_shape.tolist()
            })
        except:
            print(f"WARNING: no body contour for patient {patient_dir}, moving on")
            # body_index_range , body_mask_shape = np.array([]), np.array([])
        
    
    json_object = json.dumps(patient_dict_list, indent=4)
    with open(pth_output_json, "w") as outfile:
        outfile.write(json_object)

@app.command(
    help="""Purpose: to crop the egsphant file of all patients in a directory.""")
def crop_egsphant_by_bodyContour_many_patients(
    patient_egsphant_dir:Annotated[str, typer.Argument(
        help=""" the directory holding patient folders inside which there is .egsphant files to be cropped. \n
        Example: 
        patient_egsphant_dir/p1/ct.egsphant
        patient_egsphant_dir/p2/ct.egsphant ...""")], 
    patient_body_range_json:Annotated[str, typer.Argument(
        help="""a json file holding the list of the patient directory names as well as the index bounding range of the body contour and the original size of the body mask. This file can be generated by running the function dicom_utils.get_bodyContourRange_from_many_patients_dicom().\n
        Example: [{"patient_number": "p1", "body_index_range": [[x_min, x_max], [y_min, y_max], [z_min,z_max]], "body_mask_shape": [512, 512, 42]}, ...] """)]):
    r"""
    Purpose: 
    to crop the egsphant file of all patients in a directory. 
    Input:
    - patient_egsphant_dir := the directory holding patient folders inside which 
    there is .egsphant files to be cropped. Example:
        patient_egsphant_dir/p1/ct.egsphant
        patient_egsphant_dir/p2/ct.egsphant
        ...
    - patient_body_range_json := a json file holding the list of the patient directory names
    as well as the index bounding range of the body contour and the original size of the body mask. 
    This file can be generated by running the function dicom_utils.get_bodyContourRange_from_many_patients_dicom(). 
    run "python dicom_utils.py get_bodyContourRange_from_many_patients_dicom --help" for more details.  
    Example:
    [
        {
        "patient_number": "p1",
        "body_index_range": [
            [x_min, x_max],
            [y_min, y_max],
            [z_min,z_max]
        ],
        "body_mask_shape": [512, 512, 42]
        }
    ]
    Output:
    - Void: the cropped .egsphant file for each patient will be written to patient_dir/cropped_basename.egsphant 
    """
    pth_egsphant_set = set(glob(patient_egsphant_dir+"/*/*.egsphant"))
        
    body_range_dict = _load_json(pth_json=patient_body_range_json)

    for patient in tqdm(body_range_dict):
        pth_egsphant = list(filter(lambda x: patient["patient_number"] in x, pth_egsphant_set))[0]
        print(f"loading the patient egsphant {pth_egsphant}")
        egsphant_obj = BrachyEgsphant(pth_egsphant)
        egsphant_obj.crop_by_bodyContour(patient["body_index_range"], patient["body_mask_shape"])
        pth_cropped_egsphant = os.path.dirname(pth_egsphant) + "/cropped_" + os.path.basename(pth_egsphant)
        print(f"writing the cropped egsphant to {pth_cropped_egsphant}")
        egsphant_obj.write_to_ctegsphant(pth_cropped_egsphant)


def convert_single_dose_file(input_name, type_out):
    assert os.path.exists(input_name)
    file_base_noExtension = os.path.splitext(input_name)[0]
    if not os.path.exists(file_base_noExtension+type_out):  
        dose_obj = BrachyDose(input_name)
        dose_obj.write_brachydose_to_file(file_base_noExtension+type_out)

@app.command(help="""Will convert all files in the "input_dir" of type "type_in" to "type_out" """)
def convert_dose_many_files(
    type_out: Annotated[str, typer.Argument(help="""extension of the output files. Options are .3ddose, .nrrd, .minidos""")], 
    file_regex: Annotated[str, typer.Argument(help="""regular expression of files to be converted. for example, "*.nrrd".""")]=None,
    input_dir: Annotated[str, typer.Argument(help="""directory where there are dose files to be converted""")]=None, 
    type_in: Annotated[str, typer.Argument(help="""extension of the files to be converted. Options are .3ddose, and .nrrd. .minidos will be added soon""")]=None, 
    multi_proc:Annotated[bool, typer.Option(help="""if set to true, multiprocessing will be used to convert files in parallel""")]=False):
    r"""
    Purpose:
        Will convert all files in the "input_dir" of type "type_in" to "type_out"
    Inputs:
        input_dir := directory where there are dose files to be converted 
        type_in := could be ".3ddose", ".nrrd", ".minidos", other types could be added
        type_out := could be ".3ddose", ".nrrd", ".minidos", other types could be added
    """
    if file_regex is not None:
        file_list = glob(file_regex)
        print(file_list)
    elif input_dir is not None and type_in is not None:
        input_dir = os.path.abspath(input_dir)
        assert os.path.exists(input_dir)
        file_list = glob(input_dir+"/*"+type_in)
    else:
        raise Exception("either file_regex or input_dir and type_in should be provided")
    
    if multi_proc:
        with Pool() as our_pool:
            partial_dose_writer = partial(convert_single_dose_file, type_out=type_out) 
            our_pool.map(partial_dose_writer, file_list)
    else:
        for single_file in tqdm(file_list):
            print(f"converting {single_file}")
            convert_single_dose_file(single_file, type_out)  

@app.command(help="""Purpose: to crop all the dose files in a folder""")
def crop_dose_by_bodyContour_many_files(
    patient_dose_dir:Annotated[str, typer.Argument(help="""the directory holding patient dose files inside which there is .3ddose files to be cropped. Example: p1/run_1.3ddose, p1/run_2.3ddose""")], 
    patient_body_range_json:Annotated[str, typer.Argument(help="""a json file holding the list of the patient directory names as well as the index bounding range of the body contour and the original size of the body mask. This file can be generated by running the function dicom_utils.get_bodyContourRange_from_many_patients_dicom().\n \
        Example: [{"patient_number": "p1", "body_index_range": [[x_min, x_max], [y_min, y_max], [z_min,z_max]], "body_mask_shape": [512, 512, 42]}, ...] """)],
    type_in: Annotated[str, typer.Option(help="""could be ".3ddose", ".nrrd", ".minidos", other types could be added """)] = ".3ddose", 
    type_out: Annotated[str, typer.Option(help="""could be ".3ddose", ".nrrd", ".minidos", other types could be added """)] = ".nrrd"):    
    r"""
    Purpose: 
        to crop all the dose files in a folder
    Input:
        patient_dose_dir := the directory holding patient dose files inside which 
            there is .3ddose files to be cropped. Example:
                p1/run_1.3ddose
                p1/run_2.3ddose
            ...
        patient_body_range_json := a json file holding the list of the patient directory names
            as well as the index bounding range of the body contour and the original size of the body mask. 
            This file can be generated by running the function dicom_utils.get_bodyContourRange_from_many_patients_dicom(). 
            run "python dicom_utils.py get_bodyContourRange_from_many_patients_dicom --help" for more details.  
            Example:
                [
                    {
                    "patient_number": "p1",
                    "body_index_range": [
                        [x_min, x_max],
                        [y_min, y_max],
                        [z_min,z_max]
                    ],
                    "body_mask_shape": [512, 512, 42]
                    }
                ]
    Output:
        - Void: the cropped dose file in .nrrd format will be written to patient_dir/cropped_basename.nrrd 
    """
    type_in_out=[type_in, type_out]
    list_3ddose = glob(patient_dose_dir+"/*"+type_in_out[0])
        
    body_range_dict = _load_json(pth_json=patient_body_range_json)
    print(patient_dose_dir)
    patient_number = os.path.basename(patient_dose_dir)
    patient = list(filter(lambda x: patient_number == x["patient_number"], body_range_dict))[0] 

    print(f"the patient body mask is {patient}")

    for dose_file in tqdm(list_3ddose):
        pth_cropped_dose = os.path.dirname(dose_file) + "/cropped_" + os.path.basename(dose_file).split(".")[0]+type_in_out[1]
        # skip the nrrd files that already exist
        if os.path.exists(pth_cropped_dose):
            print(f"file already exists: {pth_cropped_dose}")
            continue
        
        print(f"loading the patient dose file at {dose_file}")
        dose_obj = BrachyDose()
        dose_obj.load_file_to_brachydose(dose_file)
        dose_obj.crop_by_body_contour(patient["body_index_range"], patient["body_mask_shape"])
        
        print(f"writing the cropped egsphant to {pth_cropped_dose}")
        dose_obj.write_to_nrrd(pth_cropped_dose)

@app.command(help=""" Purpose: Will crop all files in the "input_dir" of type "type_in" and write the cropped dose to file with "type_out" """)
def crop_dose_by_ratio_many_files(
    input_dir: Annotated[str, typer.Argument(help="""directory where there are dose files to be cropped and converted to be converted""")], 
    crop_ratio: Annotated[float, typer.Argument(help="""the fraction of the image axis that remains in the crop. for example, a crop ratio of 0.5 will keep the center of the x and y axis plus minus 0.25*dimension of the image. The x axis will not be cropped""")],
    type_in: Annotated[str, typer.Argument(help="""could be ".3ddose", ".nrrd", ".minidos", other types could be added """)], 
    type_out: Annotated[str, typer.Argument(help="""could be ".3ddose", ".nrrd", ".minidos", other types could be added """)]):
    r"""
    Purpose:
        Will crop all files in the "input_dir" of type "type_in" and write the cropped dose to file with "type_out"
    Inputs:
        input_dir := directory where there are dose files to be cropped and converted to be converted 
        crop_ratio := the fraction of the image axis that remains in the crop. for example, a crop ratio of 0.5 will keep 
            the center of the x and y axis plus minus 0.25*dimension of the image. The x axis will not be cropped. 
            +++++++++       ---------
            +++++++++       --+++++--
            +++++++++  ===> --+++++--
            +++++++++       --+++++--
            +++++++++       ---------
        type_in := could be ".3ddose", ".nrrd", ".minidos", other types could be added
        type_out := could be ".3ddose", ".nrrd", ".minidos", other types could be added
    """
    input_dir = os.path.abspath(input_dir)
    assert os.path.exists(input_dir)
    file_list = glob(input_dir+"/*"+type_in)
    
    for file in tqdm(file_list):
        dose_obj = BrachyDose()
        dose_obj.load_file_to_BrachyDose(file)
        dose_obj.crop_by_fraction(crop_ratio)

        file_base_noExtension = os.path.splitext(file)[0]

        dose_obj.write_brachydose_to_file(file_base_noExtension+type_out)
        


@app.command()
def padd_dose_many_files(input_dir: str, type_in: str, dim_out:str):
    r"""
    Purpose:
        Will padd all files in the "input_dir" of type "type_in" with zeros to
            have the dimensions "dim_out"
    Inputs:
        input_dir := directory where there are files to be converted 
        type_in := could be ".3ddose", ".nrrd", ".minidos", other types could be added
        dim_out := the new dimensions in [z, y, x] format
    """
    raise Exception("This feature is not implementated yet")

def multiply_dose_by_constant_single_file(input_name, scale_factor):
    assert os.path.exists(input_name)
    output_name = os.path.dirname(input_name) + "/scaled_" + os.path.basename(input_name)
    if not os.path.exists(output_name):
        dose_obj = BrachyDose(input_name)
        dose_obj.multiply_dose_by_constant(scale_factor)
        dose_obj.write_brachydose_to_file(output_name)
    
@app.command(help="""Purpose: Will scale all files in the "input_dir" of type "type_in" by multiplying them by "scale_factor" """)
def multiply_dose_by_constant_many_files(
    input_dir: Annotated[str,  typer.Argument(help="""directory where there are files to be converted""")],
    type_in: Annotated[str,  typer.Argument(help="""could be ".3ddose", ".nrrd", ".minidos", other types could be added""")],
    scale_factor: Annotated[float, typer.Argument(help="""the factor by which the dose will be scaled""")],
    multi_proc: Annotated[bool, typer.Option(help="""if set to true, multiprocessing will be used to convert files in parallel""")] = False):
    r"""
    Purpose:
        Will scale all files in the "input_dir" of type "type_in" 
        by multiplying them by "scale_factor". 
    Inputs:
        input_dir := directory where there are files to be converted 
        type_in := could be ".3ddose", ".nrrd", ".minidos", other types could be added
        scale_factor := the factor by which the dose will be scaled
    """
    # raise Exception("This feature is not implementated yet")
    assert os.path.exists(input_dir)
    
    file_list = glob(input_dir+"/*"+type_in)
    
    if multi_proc:
        with Pool() as our_pool:
            partial_dose_writer = partial(multiply_dose_by_constant_single_file, scale_factor=scale_factor) 
            our_pool.map(partial_dose_writer, file_list)
    else:
        for single_file in tqdm(file_list):
            multiply_dose_by_constant_single_file(single_file, scale_factor)

@app.command(help="""Purpose: Will calculate the uncertainty of all structures for all patients in a directory""")
def get_uncertainty_one_patient(
    dir_doseRate_maps:Annotated[str, typer.Argument(help="""directory containing Dose data of many patients. each folder has a subfolder for every patient. The names of the patients (subfolders) should match. """)],
    dir_plan:Annotated[str, typer.Argument(help="""directory containing Plan data of many patients. each folder has a subfolder for every patient. The names of the patients (subfolders) should match. In this folder, there should be a file named catheter_table.json that contains the catheter table.""")],
    dir_dicom:Annotated[str, typer.Argument(help="""directory containing DICOM data of many patients. each folder has a subfolder for every patient. The names of the patients (subfolders) should match.""")],
    pth_dvh_metric_goals_json:Annotated[str, typer.Argument(help="""path to the json file where the DVH metric goals are saved.""")],
    pth_uncertainty_json:Annotated[str, typer.Argument(help="""path to the json file where the uncertainty of all structures will be saved.""")],
    multi_proc:Annotated[bool, typer.Option(help="""If set to true, multiprocessing will be used to load the dose files in parallel.""")]=False,
):
    r"""
    Purpose: 
        To loop over all patients and get the uncertainty of all structures. 
    Input:
        - dir_doseRate_maps := Directory containing Dose rate maps for the dwell position. 
        - dir_plan := Directory containing Plan data of the patient. Inside the dir plan, 
        - dir_dicom := Directory containing DICOM data of the patient. 
        there should be a file named catheter_table.json that contains the catheter table.
        - pth_dvh_metric_goals_json := path to the json file where the DVH metric goals are saved.
        - pth_uncertainty_json := path to the json file where the uncertainty of all structures will be saved.
        - multi_proc := If set to true, multiprocessing will be used to load the dose files in parallel.
    Output:
        - Void := Path of the json file where the uncertainty of all structures will be saved.
    Dependencies:
    """
    
    assert os.path.exists(dir_dicom)
    assert os.path.exists(dir_doseRate_maps)
    
    with open(pth_dvh_metric_goals_json, "r") as dvh_target_file:
        dvh_metric_goals = json.load(dvh_target_file) 
    
    patient = os.path.basename(os.path.normpath(dir_doseRate_maps))
    pth_plan = dir_plan + "/catheter_table.json"
    assert os.path.exists(pth_plan)
    pth_dicom = dir_dicom + "/"
    assert os.path.exists(pth_dicom)
    pth_dose = dir_doseRate_maps + "/"
    assert os.path.exists(pth_dose)
    
    plan_obj = BrachyPlan(
        pth_catheterTable_json=pth_plan,
        dir_dose_rate=pth_dose,
        load_uncertainty=True,
        multi_processing=multi_proc,
        dvh_metric_goals=dvh_metric_goals,
        dir_structure_source=pth_dicom,
        dose_cropped_by_body=True,
    )
    plan_obj.calculate_uncertainty_per_structure()
    
    patient_info = {
        "patient_id": patient,
        "pth_dicom": pth_dicom,
        "pth_dose": pth_dose,
        "pth_plan": pth_plan,
        }
    for structure in plan_obj.structure_list:
        patient_info[structure.name] = {
            "uncertainty_mean" : structure.uncertainty_mean, 
            "uncertainty_std" : structure.uncertainty_std, 
            "uncertainty_max" : structure.uncertainty_max, 
            "uncertainty_min" : structure.uncertainty_min, 
        }

    del plan_obj
    gc.collect()

    with open(pth_uncertainty_json, "w") as outfile:
        json.dump(patient_info, outfile, indent=4)
    
def test_get_bodyContourRange_from_many_patients_dicom():
    r"""Outdated test function"""
    raise Exception("Outdated test function")
    input_dir = "../../data_test"
    pth_json = "../../data_test/test_patient_body_bounds.json"
    
    get_bodyContourRange_from_many_patients_dicom(input_dir, pth_json)
    
    with open(pth_json, "r") as file:
        data_json = json.load(file)
    
    print(data_json)

def test_crop_egsphant_by_bodyContour_many_files():
    # test on testing dataset
    pth_input = "../.."
    pth_json = "../../data_test/test_patient_body_bounds.json"
    
    # test on all patients
    # pth_input = "/home/majd/data/patient_dose_simulations/prostate-glen-1mm"
    # pth_json = "../../data_test/patient_body_bounds.json"
    
    crop_egsphant_by_bodyContour_many_patients(pth_input, pth_json)

def test_convert_many_files():
    r"""Outdated test function"""
    raise Exception("Outdated test function")
    # dir_in = "../../data_test/many_files"
    dir_in = "/home/majd/data/patient_dose_simulations/prostate-glen/p10/"
    type_in = ".nrrd"
    type_out = ".minidos"
    
    convert_many_dose_files(dir_in, type_in, type_out)
    
    dir_in = os.path.abspath(dir_in)
    nrrd_list = glob(dir_in+".nrrd")
    
    
    for file_nrrd in nrrd_list:
        dose_obj_nrrd = BrachyDose()
        dose_obj_nrrd.load_file_to_BrachyDose(file_nrrd)
        
        file_3ddose = os.path.splitext(file_nrrd)[0]+".3ddose"
        dose_obj_3ddose = BrachyDose()
        dose_obj_3ddose.load_file_to_BrachyDose(file_3ddose)
        
        dose_obj_3ddose.is_equal(dose_obj_nrrd)

def test_crop_by_bodyContour():
    pth_dicomRS = "../../data_test/prostate_glen_p1/"
    pth_3ddose = "../../data_test/run_1_glen_prostate_p1.3ddose"


    dose_obj = BrachyDose()
    dose_obj.load_file_to_BrachyDose(pth_3ddose)
    dose_obj.info()
    dose_obj.crop_by_bodyContour(pth_dicomRS)
    dose_obj.info()

def test_crop_dose_by_bodyContour_many_files():
    # pth_3ddose = "/home/majd/data/patient_dose_simulations/prostate-glen-1mm/p3/run_29.3ddose"
    pth_3ddose = "/home/majd/data/patient_dose_simulations/prostate-glen-1mm/p3"
    pth_json = "../../data_test/patient_body_bounds.json"
    
    crop_dose_by_bodyContour_many_files(pth_3ddose, pth_json)

def test_multiply_dose_by_constant_many_files():
    dir_in = "../../data_test/many_files"
    type_in = ".nrrd"
    scale_factor = 3.4
    
    multiply_dose_by_constant_many_files(
        dir_in, 
        type_in, 
        scale_factor, 
        multi_proc=True)
    
    scaled_file_list = glob(dir_in+"/scaled_*"+type_in)
    for scaled_dose_file_name in scaled_file_list:
        scaled_dose_obj = BrachyDose(scaled_dose_file_name)

        original_dose_file_name = os.path.dirname(scaled_dose_file_name) + "/" + os.path.basename(scaled_dose_file_name).split("scaled_")[-1] 
        original_dose_obj = BrachyDose(original_dose_file_name)
        
        assert np.allclose(scaled_dose_obj.grid, original_dose_obj.grid*scale_factor)

def test_get_uncertaintyAllStructures_many_patients():
    dir_dicom = "/home/majd/data/patient_treatment_plans/dicom/prostate-glen-2023/p1"
    dir_doseRate_maps = "/home/majd/data/patient_dose_simulations/prostate-glen-2023-1mm/p1"
    dir_plan = "/home/majd/data/patient_treatment_plans/tps_exported/prostate-glen-2023/p1"
    pth_json = "/home/majd/data/patient_treatment_plans/tps_exported/prostate-glen-2023/p1/patient_uncertainty.json"
    multi_proc = True
    pth_dvh_metric_goals_json = "../../data_test/dvh_metric_goals.json"
    
    get_uncertainty_one_patient(
        dir_doseRate_maps,
        dir_plan,
        dir_dicom,
        pth_dvh_metric_goals_json,
        pth_json,
        multi_proc,
    )
    
def main():
    app()

# if __name__ == "__main__":
#     # test_convert_many_files()
#     # test_crop_dose_by_bodyContour_many_files()
#     # test_multiply_dose_by_constant_many_files()
#     test_get_uncertaintyAllStructures_many_patients()