from glob import glob
import json
import os
from tqdm import tqdm
import pytest


from dicom_utils import  get_body_index_range
from egsphant_utils import _load_json, BrachyEgsphant
from dose_utils import BrachyDose
import typer

app = typer.Typer()

@app.command()
def get_body_contour_range_from_many_patients_dicom(
    input_dir:str, 
    pth_output_json:str 
):
    r"""
    Purpose:
        to exract body contour extent on each axis for all the patients in input_dir and save them
            to a json file located at "output_json"
    Input:
        - input_dir := path to the directory where folders of many patients with dicom files exist.
            this script will loop through patient folders. Example:
                input_dir/p1/
                input_dir/p2/ ...
        - output_json := path to the json file where the following information for each patient is stored            
    Output: 
        - Void := the following content will be written to output_json for each patient:
            {
                patient_number:=str,
                body_index_range:[
                    [x_min:int, x_max:int],
                    [y_min:int, y_max:int],
                    [z_min:int, z_max:int],
                ]
                body_mask_shape:[len(x):int, len(y):int, len(z):int]
            }
    """
    
    input_dir = os.path.abspath(input_dir)
    
    patient_dir_list = glob(input_dir+"/*/")
    patient_dict_list = []
    
    for patient_dir in patient_dir_list:
        try:
            body_index_range , body_mask_shape = get_body_index_range(patient_dir)
            patient_dict_list.append(
            {
            "patient_number": patient_dir.split("/")[-2],
            "body_index_range": body_index_range.tolist(),
            "body_mask_shape": body_mask_shape.tolist()
            })
        except:
            print(f"WARNING: no body contour for patient {patient_dir}, moving on")
            # body_index_range , body_mask_shape = np.array([]), np.array([])
        
    
    json_object = json.dumps(patient_dict_list, indent=4)
    with open(pth_output_json, "w") as outfile:
        outfile.write(json_object)

@app.command()
def crop_egsphant_by_body_contour_many_patients(patient_egsphant_dir:str, patient_body_range_json:str):
    r"""
    Purpose: 
        to crop the egsphant file of all patients in a directory. 
    Input:
        patient_egsphant_dir := the directory holding patient folders inside which 
            there is .egsphant files to be cropped. Example:
                patient_egsphant_dir/p1/ct.egsphant
                patient_egsphant_dir/p2/ct.egsphant
            ...
        patient_body_range_json := a json file holding the list of the patient directory names
            as well as the index bounding range of the body contour and the original size of the body mask. 
            This file can be generated by running the function dicom_utils.get_body_contour_range_from_many_patients_dicom(). 
            run "python dicom_utils.py get_body_contour_range_from_many_patients_dicom --help" for more details.  
            Example:
                [
                    {
                    "patient_number": "p1",
                    "body_index_range": [
                        [x_min, x_max],
                        [y_min, y_max],
                        [z_min,z_max]
                    ],
                    "body_mask_shape": [512, 512, 42]
                    }
                ]
    Output:
        - Void: the cropped .egsphant file for each patient will be written to patient_dir/cropped_basename.egsphant 
    """
    pth_egsphant_set = set(glob(patient_egsphant_dir+"/*/*.egsphant"))
        
    body_range_dict = _load_json(pth_json=patient_body_range_json)
    for patient in tqdm(body_range_dict): 
        pth_egsphant = list(filter(lambda x: patient["patient_number"] in x, pth_egsphant_set))[0]
        
        egsphant_obj = BrachyEgsphant(pth_egsphant)
        egsphant_obj.crop_by_body_contour(patient["body_index_range"], patient["body_mask_shape"])
        egsphant_obj.write_to_ctegsphant(
            os.path.dirname(pth_egsphant) + "/cropped_" + os.path.basename(pth_egsphant)
            )


@app.command()
def convert_many_files(input_dir: str, type_in: str, type_out: str):
    r"""
    Purpose:
        Will convert all files in the "input_dir" of type "type_in" to "type_out"
    Inputs:
        input_dir := directory where there are files to be converted 
        type_in := could be ".3ddose", ".nrrd", ".minidose", other types could be added
        type_out := could be ".3ddose", ".nrrd", ".minidose", other types could be added
    """
    input_dir = os.path.abspath(input_dir)
    assert os.path.exists(input_dir)
    file_list = glob(input_dir+"/*"+type_in)
    
    for single_file in tqdm(file_list):
        dose_obj = BrachyDose()
        dose_obj.load_file_to_BrachyDose(single_file)
        
        file_base_noExtension = os.path.splitext(single_file)[0]
        
        if type_out == ".3ddose":
            dose_obj.write_to_3ddose_file(file_base_noExtension+type_out)
        elif type_out == ".nrrd":
            dose_obj.write_to_nrrd_file(file_base_noExtension+type_out)
        elif type_out == ".minidose":
            dose_obj.write_to_minidose_file(file_base_noExtension+type_out)
        elif type_out == ".xz":
            dose_obj.write_to_xz_file(file_base_noExtension+type_out)
        elif type_out == ".npz":
            dose_obj.write_to_npz_file(file_base_noExtension+type_out)
        elif type_out == ".zstd":
            dose_obj.write_to_zstd_file(file_base_noExtension+type_out)


@app.command()
def crop_by_ratio_and_convert_many_files(input_dir: str, crop_ratio:float, type_in: str, type_out: str):
    r"""
    Purpose:
        Will crop all files in the "input_dir" of type "type_in" and write the cropped dose to file with "type_out"
    Inputs:
        input_dir := directory where there are files to be converted 
        crop_ratio := the fraction of the image axis that remains in the crop. for example, a crop ratio of 0.5 will keep 
            the center of the x and y axis plus minus 0.25*dimension of the image. The x axis will not be cropped. 
            +++++++++       ---------
            +++++++++       --+++++--
            +++++++++  ===> --+++++--
            +++++++++       --+++++--
            +++++++++       ---------
        type_in := could be ".3ddose", ".nrrd", ".minidose", other types could be added
        type_out := could be ".3ddose", ".nrrd", ".minidose", other types could be added
    """
    input_dir = os.path.abspath(input_dir)
    assert os.path.exists(input_dir)
    file_list = glob(input_dir+"/*"+type_in)
    
    for file in tqdm(file_list):
        dose_obj = BrachyDose()
        dose_obj.load_file_to_BrachyDose(file)
        dose_obj.crop_by_fraction(crop_ratio)

        file_base_noExtension = os.path.splitext(file)[0]

        if type_out == ".3ddose":
            dose_obj.write_to_3ddose_file(file_base_noExtension+type_out)
        elif type_out == ".nrrd":
            dose_obj.write_to_nrrd_file(file_base_noExtension+type_out)
        elif type_out == ".minidose":
            dose_obj.write_to_minidose_file(file_base_noExtension+type_out)
        elif type_out == ".xz":
            dose_obj.write_to_xz_file(file_base_noExtension+type_out)
        elif type_out == ".npz":
            dose_obj.write_to_npz_file(file_base_noExtension+type_out)
        elif type_out == ".zstd":
            dose_obj.write_to_zstd_file(file_base_noExtension+type_out)


@app.command()
def padd_many_files(input_dir: str, type_in: str, dim_out:str):
    r"""
    Purpose:
        Will padd all files in the "input_dir" of type "type_in" with zeros to
            have the dimensions "dim_out"
    Inputs:
        input_dir := directory where there are files to be converted 
        type_in := could be ".3ddose", ".nrrd", ".minidose", other types could be added
        dim_out := the new dimensions in [z, y, x] format
    """
    raise Exception("This feature is not implementated yet")



def test_get_body_contour_range_from_many_patients_dicom():
    input_dir = "../../data_test"
    pth_json = "../../data_test/test_patient_body_bounds.json"
    
    get_body_contour_range_from_many_patients_dicom(input_dir, pth_json)
    
    with open(pth_json, "r") as file:
        data_json = json.load(file)
    
    print(data_json)

def test_crop_egsphant_by_body_contour_many_files():
    # test on testing dataset
    pth_input = "../.."
    pth_json = "../../data_test/test_patient_body_bounds.json"
    
    # test on all patients
    # pth_input = "/home/majd/data/patient_dose_simulations/prostate-glen-1mm"
    # pth_json = "../../data_test/patient_body_bounds.json"
    
    crop_egsphant_by_body_contour_many_patients(pth_input, pth_json)

def test_convert_many_files():
    dir_in = "../../data_test/many_files"
    type_in = ".3ddose"
    type_out = ".nrrd"
    
    convert_many_files(dir_in, type_in, type_out)
    
    dir_in = os.path.abspath(dir_in)
    nrrd_list = glob(dir_in+".nrrd")
    
    for file_nrrd in nrrd_list:
        dose_obj_nrrd = BrachyDose()
        dose_obj_nrrd.load_file_to_BrachyDose(file_nrrd)
        
        file_3ddose = os.path.splitext(file_nrrd)[0]+".3ddose"
        dose_obj_3ddose = BrachyDose()
        dose_obj_3ddose.load_file_to_BrachyDose(file_3ddose)
        
        dose_obj_3ddose.is_equal(dose_obj_nrrd)

def test_crop_by_body_contour():
    pth_dicomRS = "../../data_test/prostate_glen_p1/"
    pth_3ddose = "../../data_test/run_1_glen_prostate_p1.3ddose"


    dose_obj = BrachyDose()
    dose_obj.load_file_to_BrachyDose(pth_3ddose)
    dose_obj.info()
    dose_obj.crop_by_body_contour(pth_dicomRS)
    dose_obj.info()

def main():
    app()

# if __name__=="__main__":
# #     # test_get_body_contour_range_from_many_patients_dicom()
#     app()
